runtime: python
env: flex

service: social-media-analytics

runtime_config:
  python_version: 3

# instance_class: F4

entrypoint: streamlit run app.py --address 0.0.0.0 --port 8080 --allow-websockets-origin="+"

manual_scaling:
  instances: 2
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

